name: Execute Shell Script for CI

on:
  push:
    branches:
      - main

jobs:
  run-shell-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Execute shell script
        run: |
          chmod +x ../../buildbot-ci/script.sh
          ../../buildbot-ci/script.sh
